### ISSUE TITLE
channel data not matching channel name for version > 1.1.12

### ISSUE THREAD

**Issue by phwolf** [domna/tdm_loader#17]
First of all, thank you very much for this great package!
We used this to successfully parse large amounts of tdm files.
 
Recently I noticed that the some of the recently parsed tdm files were corrupt, meaning that the channels haven't been mapped correctly to their corresponding channel names (e.g. for channel A we got data from some other channel C and for channel C we got data from B and so on). The export type of these files is National Instruments USI. For Version 1.1.12 everything works as expected, for version 1.1.14 & 1.1.15 I noticed the problems mentioned above.
Any ideas what changed from 1.1.12 that could cause that behavior?

**Comment by domna** [comment]
Hey,

yes I actually changed the way the data is parsed from the XML file to actually get corresponding binary data. Obviously there is some faulty behaviour regarding the mapping based on channel names.

I will look into this issue in the next days. Do you have any example file on which I could test?

**Comment by phwolf** [comment]
I cannot give you the original data, but I will try to create some test data

**Comment by domna** [comment]
Can you give me the function call you use to extract your data?

**Comment by phwolf** [comment]
We iterate over groups and channels and create for each group a dataframe:
```python
file = tdm_loader.OpenFile('some_data.tdm', encoding='utf-8')

for i in range(file.no_channel_groups()):
    for j in range(file.no_channels(i)):
        # print(file.channel_name(i,j), file.channel(i,j))
        # for each group i we create a dataframe
        # with column names file.channel_name(i,) and content file.channel(i,)

file.close()
```

**Comment by domna** [comment]
Have you tried the channel_dict(channel_group) function?
It will give you a dictonary of a channel group with the channel names as keys. It would be interesting for me if it is correct in this case.

**Comment by phwolf** [comment]
Yes, I also tried channel_dict(). The behavior was the same, channels and channel were not correctly mapped.

**Comment by morbult** [comment]
Hi, I too noticed this problem. I cannot send any original data either, but [here](https://github.com/domna/tdm_loader/files/2988964/output.txt) is the output of the following script where I use a file with 1 group and 40 channels and print each channel data using four methods.

```py
data_file = tdm_loader.OpenFile('my_data.tdm')

for i in range(data_file.no_channels(0)):
    name = data_file.channel_name(0, i)
    print('channel', i)
    print(data_file.channel(0, i))
    print(data_file.channel(0, name))
    print(data_file[0, i])
    print(data_file[name])
    print()
```

You can see that the 2nd method `data_file.channel(0, name)` gives different data, and it's often (but not always) shifted by 1 channel index. However, for channel 0 (which should be Time) all methods give the same data but it's clearly not Time.

Hope this can give you some clues!

**Comment by domna** [comment]
Hey, I made a quick fix to the reading of the data. For me everything looks good. I also dropped the reading of string_sequences (that's why @phwolf files did not work), because they are represented in the XML file and not as binary data (I may fix this in the future, but for now string channels are simply ignored).

Since at the moment I do not have the time to thoroughly test this, I just commited the changes and you are free to test and I would be glad if you could check if there are still some errors with your files.

**Comment by phwolf** [comment]
Hi, thanks for the fixes!
I tested with some of my files, but I still have some issues. For the first group everything works out for me. But for the other groups I get some discrepancies when comparing with earlier results produced with tdm_loader version 1.1.12. The time channel seems to be fine though. But for the other channels the values differ.

**Comment by domna** [comment]
How do you read the data? By column number or by name?
I changed the way column numbers are adressed (because there was a discrepancy in there, which was the origin for the above error). The scheme I use now should be more adequate, as it maps directly to the ordering of the binary data.
Could you check if the assignment of channel name and number is correct and consistent?
To keep backward compatibility I could implement the new ordering in a separate function if this is important to you.

Thank you for testing!

**Comment by morbult** [comment]
Thank you for this fix! Version 1.1.16 is now usable for me.
However, there is still some discrepancy. I used the same script as in my [last post](https://github.com/domna/tdm_loader/issues/17#issuecomment-474897416) and [here](https://github.com/domna/tdm_loader/files/3072560/output_v1.1.16.txt) is the new output.
You can see that the 2nd method again gives different data, but now only for channel 0 and one other, in this case channel 10. And that data is equal to the data of the last channel, in this case channel 39. I have checked two different tdm files and this is true for both of them.

Anyway, `data_file.channel_dict(0)` works fine so I'm happy about the fix.

Edit: I have also verified that the channel data I get from `data_file.channel_dict(0)` is in fact correct and correctly mapped to the channel names by comparing with data converted from tdm by a commercial software.

**Comment by domna** [comment]
Is it possible that the name of channel 0 and 10 have some special characters in them or have the same name?

It looks like the mapping is not working correct and the script just gets the last channel because it can not find the channel with the name given in the function. I will have a look at the code if I can find any clue supporting this idea.

**Comment by morbult** [comment]
No, they don't have any special charactes or spaces in their names in the two files I tested. I can't see anything special about those two channels except that the first one is channel 0, which is time, in both files.

Could there be something in the implementation of `data_file.channel(0, name)`, since `data_file[name]` works fine?

**Comment by domna** [comment]
Yes there is actually a difference in how strings get parsed to channel indices.
The channel function gets its indices from the XML structure in the TDM file and I don't know why this fails for just two channels in the data set.
I could use the same function from __getitem__ but its not able to handle duplicate channel names, but if it is important to you I could commit this fix until I have time to thoroughly construct test files and fix the problem on the XML level.

**Comment by domna** [comment]
I rewrote the internal representation of the channel enumeration.
The issue should be fixed now.
I would be glad if you could test the new version with your data files.

**Comment by domna** [comment]
Changes upstreamed to pypi in Version 1.2.0

**Comment by morbult** [comment]
Great work! This looks really nice! Sorry for the very late reply, but [here](https://github.com/domna/tdm_loader/files/3701457/output_v1.2.0.txt) is the output from the same [script](https://github.com/domna/tdm_loader/issues/17#issuecomment-474897416) as before and now it is as expected: all 4 methods give the same channel data for all 40 channels.

One note: there is a small bug in `__repr__`. It gives a RecursionError since there is no parentheses after `self.no_channel_groups`
